### ISSUE TITLE
wondering if possible to use DEoptim inside a wrapper function

### ISSUE THREAD

**Issue by frank0434** [ArdiaD/DEoptim#11]
Hi there, 

Thanks for the nice package for optimisation. 
I tried to use `DEoptim` with the `targets` package, which means I need to wrap `DEoptim` inside a function.
But `DEoptim` complains that objects can't be found when I define input variables via `parVar` in the `DEoptim.control`. 

Tracked to this line of code about the variable export: 
https://github.com/ArdiaD/DEoptim/blob/cd9818822050cb2e0b8ea97a8452daf1f347947e/R/DEoptim.R#L128

Wondering how could I pass variables into `DEoptim` inside a function? 

Many thanks

**Comment by braverock** [comment]
Many packages call DEoptim from inside other functions.

You probably need to pass the object returned by DEoptim.control

See e.g. `PortfolioAnalytics` for integrations that include use of parallelization, nested optimization, etc.

**Comment by frank0434** [comment]
@braverock Many thanks for your reply. 
Managed to pass the object by reading objects from the cache. 
Will have a look at the package you mentioned. 

Close this question.
