### ISSUE TITLE
Error in DEoptim(funct_set, lower, upper) :    objective function result has different length than parameter matrix

### ISSUE THREAD

**Issue by swaheera** [ArdiaD/DEoptim#12]
I am using the DEoptim library in R to optimize the following function:

```
library(dplyr)
library(DEoptim)

# create some data for this example
a1 = rnorm(1000,100,10)
b1 = rnorm(1000,100,10)
c1 = sample.int(1000, 1000, replace = TRUE)
train_data = data.frame(a1,b1,c1)

funct_set <- function (x) {
    x1 <- x[1]; x2 <- x[2]; x3 <- x[3] ; x4 <- x[4]; x5 <- x[5]; x6 <- x[6]; x7 <- x[7]
    f <- numeric(4)
    
    
    #bin data according to random criteria
    train_data <- train_data %>%
        mutate(cat = ifelse(a1 <= x1 & b1 <= x3, "a",
                            ifelse(a1 <= x2 & b1 <= x4, "b", "c")))
    
    train_data$cat = as.factor(train_data$cat)
    
    #new splits
    a_table = train_data %>%
        filter(cat == "a") %>%
        select(a1, b1, c1, cat)
    
    b_table = train_data %>%
        filter(cat == "b") %>%
        select(a1, b1, c1, cat)
    
    c_table = train_data %>%
        filter(cat == "c") %>%
        select(a1, b1, c1, cat)
    
    
    
    #calculate  quantile ("quant") for each bin
    
    table_a = data.frame(a_table%>% group_by(cat) %>%
                             mutate(quant = ifelse(c1 > x5,1,0 )))
    
    table_b = data.frame(b_table%>% group_by(cat) %>%
                             mutate(quant = ifelse(c1 > x6,1,0 )))
    
    table_c = data.frame(c_table%>% group_by(cat) %>%
                             mutate(quant = ifelse(c1 > x7,1,0 )))
    
    f[1] = mean(table_a$quant)
    f[2] = mean(table_b$quant)
    f[3] = mean(table_c$quant)
    
    
    #group all tables
    
    final_table = rbind(table_a, table_b, table_c)
    # calculate the total mean : this is what needs to be optimized
    
    f[4] = mean(final_table$quant)
    
    #this is the only line of code that is different between the two functions
    return (f);
}




lower <- c(80,80,80,80,100,200,300)
upper <- c(120,120,120,120,200,300,400)
## run DEoptim and set a seed first for replicability
set.seed(1234)
DEoptim(funct_set, lower, upper)

```
This returns the following error:

```
Error in DEoptim(funct_set, lower, upper) : 
  objective function result has different length than parameter matrix
```

Does anyone know why this error is being produced?
Thanks

**Comment by joshuaulrich** [comment]
Your objective function returns a 4-element vector.

```r
R$ funct_set(lower)                                                                           
[1]   NaN   NaN 0.715 0.715
R$ funct_set(upper)                                                                           
[1] 0.8079332       NaN 0.5238095 0.7960000
```

`?DEoptim` says (emphasis added) that it should contain a scalar:

>      fn: the function to be optimized (minimized). The function should
>          have as its first argument the vector of real-valued
>          parameters to optimize, **and return a scalar real result**. 'NA'
>          and 'NaN' values are not allowed.

**Comment by swaheera** [comment]
OK, thank you. This is what I thought - will DEOptim be able to handle "multi objective optimization" problems in the future?

Thanks

**Comment by joshuaulrich** [comment]
I don't speak for every contributor for the package, but I consider DEoptim to be feature-complete at this point. I'm not aware of any plans to add functionality.

Closing because this seems to be resolved. Happy to continue a discussion though.

**Comment by braverock** [comment]
There is work in the literature on multi-objective optimization using Differential Evolution.  see e.g. "Adaptive Differential Evolution" by Zhang and Sanderson.

multi-objective DE seems to compare well to NGSA-II, which is kind of the benchmark algorithm in this area.

I'd be open to a project to port the Zhang/Sanderson multi-objective DE code to `DEoptim`, if someone wanted to work on it, or e.g. as a Google Summer of Code project.  As Josh said, this is not currently a high priority.

In any case, it wouldn't work with a single objective function returning multiple objective values, but rather with multiple objective functions and some interaction described between the various objectives.
