### ISSUE TITLE
Bug when an argument named "M" is used in the target function.

### ISSUE THREAD

**Issue by LeopoldoCatania** [ArdiaD/DEoptim#2]
From the DEoptim documentation the following code works:

```
Rosenbrock <- function(x){
  x1 <- x[1]
  x2 <- x[2]
  100 * (x2 - x1 * x1)^2 + (1 - x1)^2 
}


lower <- c(-10,-10)
upper <- -lower

set.seed(1234)

DEoptim(Rosenbrock, lower, upper)
```

If we add an argument "M" to the Rosenbrock function the code does not work anymore

```
Rosenbrock <- function(x, M){
  x1 <- x[1]
  x2 <- x[2]
  100 * (x2 - x1 * x1)^2 + (1 - x1)^2 + M
}

lower <- c(-10,-10)
upper <- -lower

set.seed(1234)

M = 4

DEoptim(Rosenbrock, lower, upper, M = M)
```
error:
```
Error in match.fun(FUN) : '1' is not a function, character or symbol
```
If the extra argument is called "R" no error occurs.

**Comment by joshuaulrich** [comment]
Thanks for the report!  It looks like `M` is being partially matched to the `MARGIN` argument of `apply()`.  I'll have a fix pushed shortly.

A similar bug was fixed in ae82a815751f6c1eeaef4e51430df8fcef556af9.

**Comment by gregfaletto** [comment]
Hi, I just now encountered a similar issue in DEoptim 2.2-4. My objective function had an argument named "X" leading to the same error as above. When I renamed the variable "X.dat" it worked fine.

**Comment by joshuaulrich** [comment]
@k-m-m reverted both of these fixes for CRAN version 2.2-5 (2020-02-23) for unknown reasons. The bug was accidentally re-introduced to the development version in 53341917773a40f617694aba6ec74ec28bed6cf1.

**Comment by k-m-m** [comment]
Reverted to the changes in 24c311e - including adding tests/tests.R

**Comment by joshuaulrich** [comment]
Some of these changes were missed. I will fix.
