### ISSUE TITLE
parallelType = 1: Please avoid hard-coded detectCores() cluster

### ISSUE THREAD

**Issue by HenrikBengtsson** [ArdiaD/DEoptim#20]
When using `parallelType = 1`, we have:

https://github.com/ArdiaD/DEoptim/blob/53341917773a40f617694aba6ec74ec28bed6cf1/R/DEoptim.R#L159-L170

1. ~~This does not stop the created cluster when done. If called repeatedly, more and more parallel background workers will be running on the user's machine.  On MS Windows, these workers might not terminate when the main R session ends.~~ (not correct; see below comment)

2. Please consider not using all cores; this won't play nice on multi-user systems and will overuse the CPUs when the R process is throttle by cgroups, e.g. containers and RStudio Cloud.  A quick fix for the latter, is `parallelly::availableCores()` (<https://parallelly.futureverse.org/#availablecores-vs-paralleldetectcores>).

**Comment by HenrikBengtsson** [comment]
Correction; I found:

https://github.com/ArdiaD/DEoptim/blob/53341917773a40f617694aba6ec74ec28bed6cf1/R/DEoptim.R#L212-L213

further down.  Point 2 above remains.

**Comment by joshuaulrich** [comment]
Hi Henrik, thanks a lot for the report! Would you be willing to open a PR? I trust you and your expertise a lot more than I trust myself in this area.

**Comment by HenrikBengtsson** [comment]
Sure, PR #21 created. I made an absolutely minimal change, avoiding changing your current API.  By using `availableCores()` instead of `detectCores()`, the user can control the number of cores by setting for instance R option `mc.cores`, or [one of many other options and environment variables](https://parallelly.futureverse.org/reference/availableCores.html).

**Comment by k-m-m** [comment]
I merged this change in.

**Comment by HenrikBengtsson** [comment]
Thank you
