### ISSUE TITLE
Set default mapping function to NULL

### ISSUE THREAD

**Issue by joshuaulrich** [ArdiaD/DEoptim#24]
This was implemented in 121ae1908cdac518f16c71dbd7a92976e76e8554 on 2018-02-11, but never included in a CRAN release for some reason. This improves performance by allowing us to avoid one R call during the optimization if there is no mapping function.

**Comment by k-m-m** [comment]
fixed

**Comment by joshuaulrich** [comment]
Partially fixed in fcfe194a7f67a67af84b6eee3a4ea3795f84ce77. One call was missed. I will fix.
