### ISSUE TITLE
incrementEval is ignored

### ISSUE THREAD

**Issue by joshuaulrich** [ArdiaD/DEoptim#26]
`l_nveval` is always incremented even though `popEvaluate` has an `incrementEval` argument and is called with that set to false. This is either a regression from b1d0ba59c675d12dc412bc19604164d9da78646d or `incrementEval` should be removed and the counter should always be incremented.

**Comment by k-m-m** [comment]
added 
if(incrementEval)
     (*l_nfeval) += nr;  
-- this was done in b1d0ba5
