### ISSUE TITLE
`t_bestC` may be uninitialized

### ISSUE THREAD

**Issue by joshuaulrich** [ArdiaD/DEoptim#27]
This was fixed in 9f0eb709e51f203f238b7cc732df2ea674327d92 on 2018-02-11, but never included in a CRAN release for some reason. It could cause a segfault. The bug was accidentally re-introduced to the development version in 53341917773a40f617694aba6ec74ec28bed6cf1.

**Comment by k-m-m** [comment]
Reverted to the changes in [9f0eb70]
