### ISSUE TITLE
Remove unnecessary allocation

### ISSUE THREAD

**Issue by joshuaulrich** [ArdiaD/DEoptim#28]
This was fixed in c231be6cdf1961d73d93a3f4b1bbe648645c13c6 on 2018-02-11, but never included in a CRAN release for some reason. It could cause a segfault. The bug was accidentally re-introduced to the development version in 53341917773a40f617694aba6ec74ec28bed6cf1.

**Comment by k-m-m** [comment]
I added back in the modifications made in c231be6
