### ISSUE TITLE
Wrong cluster passed to clusterExport when both cluster and parVar are supplied

### ISSUE THREAD

**Issue by ygc2l** [ArdiaD/DEoptim#3]
Hi there,

I am getting this error `Error in parallel::clusterExport(cl, ctrl$parVar) : object 'cl' not found` when I supplied a custom cluster and set the parVar parameter in DEoptim.control().

I tracked down the issue to the line https://github.com/ArdiaD/DEoptim/blob/cran/R/DEoptim.R#L128 which should be removed or rewriten to parallel::clusterExport(ctrl$cluster, ctrl$parVar). 

I am using the DEoptim CRAN version.

**Comment by joshuaulrich** [comment]
Thanks for the report!  I will investigate to see if the issue exists in the development version.

EDIT: Yep, it's still there...

**Comment by joshuaulrich** [comment]
Fixed in #6.

**Comment by joshuaulrich** [comment]
@k-m-m reverted this fix in CRAN version 2.2-5 (2020-02-23) for unknown reasons. The bug was accidentally re-introduced to the development version in 53341917773a40f617694aba6ec74ec28bed6cf1.

**Comment by k-m-m** [comment]
reverted to fix from  Jan 20, 2019

**Comment by joshuaulrich** [comment]
Wrong line was changed. I will fix.
