### ISSUE TITLE
popEvaluate() calls objective function twice

### ISSUE THREAD

**Issue by joshuaulrich** [ArdiaD/DEoptim#30]
This looks like a bug... needs another set of eyes.
https://github.com/ArdiaD/DEoptim/blob/e9fd5edbd32719904982cd8ec3801a420b660bf3/src/evaluate.c#L16

```c
   if (isNull(fcall))
    return parMat;
   PROTECT(fn = lang3(fcall, parMat, R_DotsSymbol)); P++;  // do we need this one
   PROTECT(sexp_fvec = eval(fn, env)); P++;                // or this one?
   nr = nrows(sexp_fvec);
   if(incrementEval)
     (*l_nfeval) += nr;  
```

**Comment by k-m-m** [comment]
I don't think it is a bug (but I can look into it more tonight)- I think the first line gets the function call, the 2nd evaluates it.

**Comment by joshuaulrich** [comment]
Ah, yes. I think you're right. The variable names are confusing because they're backward.

The argument to `popEvaluate()` is `fcall`, which seems to be the function definition... not a call to it. Then the call is created and named `fn`... which is a call language object, not a function.

**Comment by k-m-m** [comment]
This interpretation seems right to me.

**Comment by joshuaulrich** [comment]
Thanks for double-checking!
