### ISSUE TITLE
Move parallelly to suggests

### ISSUE THREAD

**Issue by joshuaulrich** [ArdiaD/DEoptim#32]
Parallel functionality is optional, and it's good practice to only require it be installed if users need it.

**Comment by k-m-m** [comment]
that sounds right to me, I think that it was just slotted into where we had the parallel package.

**Comment by joshuaulrich** [comment]
Yeah, that was my guess too. And it wasn't a problem with parallel because it ships with R and so it was always available.

**Comment by k-m-m** [comment]
Changed DESCRIPTION and NAMESPACE.
