### ISSUE TITLE
Error in DEoptim::DEoptim(fn = minimizeCostValue, lower = c(unlist(minVals[!as.logical(fixedFit)]),  :    NaN value of objective function!  Perhaps adjust the bounds.

### ISSUE THREAD

**Issue by lycheeyqy** [ArdiaD/DEoptim#34]
I am using the DEoptim library in R to realize the following function:

```r
install.packages("DMCfun")
library(DMCfun)

# Change the working path
working_dir = "C:/Users/lycheeyqy/Desktop/DDM/DMC_data"

n_delta = 5
dataFiles = c("Data_Sub.csv","Data_HC.csv")

setwd(working_dir)

# Make the result folder if it doesn't exist yet
dir.create(file.path(working_dir, 'result/'), showWarnings = FALSE)

run_analysis_for_file <- function(dataFile) {
  result_dir = file.path(working_dir, 'result')
  rawData = read.csv(file.path(working_dir, 'data_prepared', dataFile))
  resOb = dmcObservedData(rawData,outlier = c(200, 2000), nDelta = n_delta)
  fitRes = dmcFitSubjectDE(resOb, 
                           minVals = list(amp = 5, resSD = 5), # minimum value instead of default DMCfun values
                           
                           maxVals = list(amp = 40, resSD = 200), # maximum value
                           
                           fixedFit = list(aaShape = T, spShape = T), # fix these parameters to increase focus
                           
                           nDelta = n_delta,
                           
                           numCores = 4 )
  
  output_file = file.path(result_dir, paste0("summary_", tools::file_path_sans_ext(dataFile), "_", Sys.Date(), ".csv"))
  write.table(summary(fitRes), file = output_file, row.names = FALSE, col.names = TRUE, sep = ",")
  
  
  pdf(file.path(result_dir, paste0("fittask_", tools::file_path_sans_ext(dataFile), ".pdf")))
  plot(fitRes, resOb, figType = "summary", legend = TRUE)  
  dev.off() 
}

lapply(dataFiles, run_analysis_for_file)
```

This returns the following error:

```
Error in DEoptim::DEoptim(fn = minimizeCostValue, lower = c(unlist(minVals[!as.logical(fixedFit)]),  : 
  NaN value of objective function! 
Perhaps adjust the bounds.
```

I have adjusted the minVal and maxVal values, but it did not work. Does anyone know why this error is being produced and how can I resolve it? It seems that this code is fine for other samples.

Thanks

**Comment by braverock** [comment]
this is not a self-contained, reproducible, example.

`dmcObservedData` and `dmcFitSubjectDE` are responsible for the returned value, and those are not part of DEoptim... they are part of your code or some other package.  The problem is almost certainly in one of these, or in your data, not in DEoptim itself.

So please provide a completely reproducible example, including these functions and a *minimal* data set that replicates the problem.

**Comment by braverock** [comment]
@lycheeyqy was my earlier query enough for you to figure out your problem?  We can try to help you, but we just need more information if you still need assistance.

**Comment by lycheeyqy** [comment]
Hi,

I have solved the problem. There is something wrong with my sample data.

Thanks.

---- Replied Message ----
| From | Brian G. ***@***.***> |
| Date | 12/18/2024 21:07 |
| To | ArdiaD/DEoptim ***@***.***> |
| Cc | lycheeyqy ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ArdiaD/DEoptim] Error in DEoptim::DEoptim(fn = minimizeCostValue, lower = c(unlist(minVals[!as.logical(fixedFit)]), : NaN value of objective function! Perhaps adjust the bounds. (Issue #34) |

@lycheeyqy was my earlier query enough for you to figure out your problem? We can try to help you, but we just need more information if you still need assistance.
