### ISSUE TITLE
Fixing a parameter through equal boundaries?

### ISSUE THREAD

**Issue by dleutnant** [ArdiaD/DEoptim#4]
Hi,

I was just wondering if it is numerically allowed to fix a parameter by setting equal boundaries?

For example
`DEoptim::DEoptim(test, lower = c(0, 0), upper = c(1,0))` would fix the second parameter to `0`
?

Thanks!

**Comment by joshuaulrich** [comment]
There's to prevent you from setting a parameter to a specific/constant value. For example:

```r
  Wild <- function(x) {
       y <- x[2]
       x <- x[1]
       10 * sin(0.3 * x) * sin(1.3 * x^2)
       + 0.00001 * x^4 + 0.2 * x + 80 + y
   }
   outDEoptim <- DEoptim(Wild, lower = c(-50, 0), upper = c(50, 0),
                         control = DEoptim.control(trace = FALSE))
```

Let us know if you have other questions.
