### ISSUE TITLE
bs = TRUE option bug

### ISSUE THREAD

**Issue by PalaceChan** [ArdiaD/DEoptim#5]
Hello, It appears from NEWS that this option had a few bugs in the past. However as of commit e1d53e96599538f63223d853e6cc7151a0ccc1bf it has been commented out. The relevant piece in the comment is "NOTE: i_bs_flag and i_check_winner have *NOT* been migrated". Curious what the nature of the remaining bug or issue may be?

**Comment by joshuaulrich** [comment]
I'm closing this because it's been ignored for so long. Happy to re-open it if it would still be useful to discuss.
