### ISSUE TITLE
Package creator

### ISSUE THREAD

**Issue by ArdiaD** [ArdiaD/DEoptim#8]
Hi @k-m-m @joshuaulrich  and @braverock 
It seems that the package creator on the current version + on CRAN is Kate. This is incorrect. May I ask the one who did this change to revert to my name, as I created it.
Thanks

**Comment by joshuaulrich** [comment]
Hi David, I assume you're referring to the "cre" in "[aut, cre]" after Katherine's name.  What that technically means "creator", CRAN uses it to signify the maintainer.  See paragraph 14 under [The DESCRIPTION file](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file) in Writing R Extensions.

**Comment by ArdiaD** [comment]
Hi @joshuaulrich. Thanks for your message and my apologies to all for that. This is all good. I worked like crazy these last days and took first-sense the "cre" field. Best wishes and stay safe!

**Comment by joshuaulrich** [comment]
Yeah, it's certainly confusing.  I only knew the answer because I was confused like you were some day in the past. ;-)
